# Generated by Django 4.2.27 on 2025-12-29 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='Оригинальный URL')),
                ('short_code', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Короткий код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Время клика')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='Тип устройства')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='Браузер')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='ОС')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('referer', models.URLField(blank=True, max_length=2000, verbose_name='Откуда пришёл')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.url', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['url', '-clicked_at'], name='shortener_c_url_id_0ecf4b_idx'), models.Index(fields=['country'], name='shortener_c_country_95f649_idx'), models.Index(fields=['device_type'], name='shortener_c_device__a7a542_idx')],
            },
        ),
    ]
