# Generated by Django 4.2.27 on 2025-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество кликов'),
        ),
        migrations.AddField(
            model_name='url',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['browser'], name='shortener_c_browser_0b9a8d_idx'),
        ),
    ]
